package dynoptic.mc;

import java.util.List;

import dynoptic.util.Util;

import synoptic.model.event.DistEventType;

/**
 * Represents a counter-example event-based path generated by McScM/SPIN or
 * another model checker. This is a list of events, which when executed by the
 * corresponding CFSM bring the system into a bad state/configuration.
 */
public class MCcExample {
    // The sequence of events that makes up the counter-example.
    private final List<DistEventType> events;

    public MCcExample() {
        events = Util.newList();
    }

    public void addScmEventStrToPath(DistEventType e) {
        events.add(e);
    }

    public List<DistEventType> getEvents() {
        return events;
    }

    @Override
    public String toString() {
        String ret = "CExample[\n";
        for (DistEventType e : events) {
            ret += "  " + e.toString() + "\n";
        }
        return ret + "]";
    }
}
