package mcscm;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a counter-example generated by McScM.
 */
public class CounterExample {
    // The sequence of events that makes up the counter-example.
    List<String> events;

    public CounterExample() {
        events = new ArrayList<String>();
    }

    public void addEvent(String event) {
        events.add(event);
    }

    public List<String> getEvents() {
        return events;
    }
}
