package synoptic.tests.units;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.junit.Test;

import synoptic.invariants.CExamplePath;
import synoptic.invariants.fsmcheck.AFbyLowerTracingSet;
import synoptic.invariants.fsmcheck.ConstrainedHistoryNode;
import synoptic.invariants.fsmcheck.ConstrainedTracingSet;
import synoptic.invariants.fsmcheck.TracingStateSet;
import synoptic.model.EventNode;
import synoptic.model.Partition;
import synoptic.model.event.Event;
import synoptic.tests.PynopticTest;
import synoptic.util.time.ITime;
import synoptic.util.time.ITotalTime;

/**
 * Tests for finding counter-example paths using TracingStateSets for
 * constrained temporal invariants
 * 
 */
public class ConstrainedTracingSetTests extends PynopticTest {

    // Events for AP tests. Traces 1 and 2 are common, and trace 3 causes there
    // to be no "x AFby z" invariant to ensure that AP tracing sets are truly
    // modeling AP FSMs
    protected String[] eventsAP = { "x 0", "y 11", "z 71", "w 72", "--",
            "x 100", "y 160", "z 171", "w 172", "--", "x 200", "u 201" };

    // Events for AFby tests. Traces 1 and 2 are common, and trace 3 causes
    // there to be no "x AP z" invariant to ensure that AFby tracing sets are
    // truly modeling AFby FSMs
    protected String[] eventsAFby = { "x 0", "y 11", "z 71", "w 72", "--",
            "x 100", "y 160", "z 171", "w 172", "--", "v 200", "z 201", "w 202" };

    /**
     * Get partitions corresponding to the A and B predicates of the current
     * constrained invariant and the terminal partition. This method is only
     * guaranteed to give _some_ partition with the label of A and of B, so
     * behavior is not guaranteed if there exists more than one A or B partition
     * in the partition graph.
     * 
     * @return 3-element array of partitions: [0] is A, [1] is B, [2] is
     *         terminal
     */
    private Partition[] getPartitions() {

        Partition[] partitions = new Partition[3];

        // Get partition of first invariant predicate ("A")
        for (Partition part : graph.getNodes()) {
            if (part.getEType().equals(inv.getFirst())) {
                partitions[0] = part;
                break;
            }
        }

        // Get partition of second invariant predicate ("B")
        for (Partition part : graph.getNodes()) {
            if (part.getEType().equals(inv.getSecond())) {
                partitions[1] = part;
                break;
            }
        }

        // Get terminal partition
        for (Partition part : graph.getNodes()) {
            if (part.isTerminal()) {
                partitions[2] = part;
                break;
            }
        }

        return partitions;
    }

    /**
     * Common code for testing failure states of tracing sets for constrained
     * invariants
     */
    private void failureStateTestCommon(String[] events, String invString,
            TracingSet type) throws Exception {

        // Get tracing sets and partitions corresponding to A and B events
        Map<Partition, TracingStateSet<Partition>> tracingSets = genConstrTracingSets(
                events, invString, type);
        Partition[] partitions = getPartitions();

        // State machine should be at an accept state at partition 'x'
        assertFalse(tracingSets.get(partitions[0]).isFail());

        // State machine should be at a failure state at partition 'z'
        assertTrue(tracingSets.get(partitions[1]).isFail());
    }

    /**
     * Check that APUpperTracingSet reaches a failure state when (and only when)
     * the time constraint is violated
     */
    @Test
    public void APUpperFailureStateTest() throws Exception {
        failureStateTestCommon(eventsAP, "x AP z upper", TracingSet.APUpper);
    }

    /**
     * Check that AFbyUpperTracingSet reaches a failure state when (and only
     * when) the time constraint is violated
     */
    @Test
    public void AFbyUpperFailureStateTest() throws Exception {
        failureStateTestCommon(eventsAFby, "x AFby z upper",
                TracingSet.AFbyUpper);
    }

    /**
     * Check that APLowerTracingSet reaches a failure state when (and only when)
     * the time constraint is violated
     */
    @Test
    public void APLowerFailureStateTest() throws Exception {
        failureStateTestCommon(eventsAP, "x AP z lower", TracingSet.APLower);
    }

    /**
     * Check that AFbyLowerTracingSet reaches a failure state when (and only
     * when) the time constraint is violated
     */
    @Test
    public void AFbyLowerFailureStateTest() throws Exception {
        failureStateTestCommon(eventsAFby, "x AFby z lower",
                TracingSet.AFbyLower);
    }

    /**
     * Common code for testing counter-example paths generated by tracing sets
     * for upper-bound constrained invariants
     */
    private void cExPathTestCommon(String[] events, String invString,
            TracingSet type) throws Exception {

        // Get tracing sets and partitions corresponding to A and B events and
        // terminal
        Map<Partition, TracingStateSet<Partition>> tracingSets = genConstrTracingSets(
                events, invString, type);
        Partition[] partitions = getPartitions();

        // Get counter-example path at the terminal partition
        CExamplePath<Partition> cExPath = tracingSets.get(partitions[2])
                .failpath().toCounterexample(inv);

        // Shorter variable aliases for cleaner assertions below
        List<Partition> path = cExPath.path;
        int vStart = cExPath.violationStart;
        int vEnd = cExPath.violationEnd;

        // Counter-example path should be (INIT -> x -> y -> z -> w -> TERM)
        assertTrue(path.size() == 6);

        // Violation subpath should start at 'x' and end at 'z'
        assertTrue(path.get(vStart).equals(partitions[0]));
        assertTrue(path.get(vEnd).equals(partitions[1]));

        // Violation subpath should be two abstract transitions long
        // (x -> y -> z)
        assertTrue(vEnd - vStart == 2);

        // Checks specific to upper-bound invariants
        if (type == TracingSet.APUpper || type == TracingSet.AFbyUpper) {
            // Counter-example path should store time at the end of violation
            // subpath as 120 after taking all max time transitions
            // ( x --60--> y --60--> z )
            ITime t120 = new ITotalTime(120);
            assertTrue(cExPath.tDeltas.get(vEnd).compareTo(t120) == 0);
        }

        // Checks specific to lower-bound invariants
        else if (type == TracingSet.APLower || type == TracingSet.AFbyLower) {
            // Counter-example path should store time at the end of violation
            // subpath as 22 after taking all min time transitions
            // ( x --11--> y --11--> z )
            ITime t22 = new ITotalTime(22);
            assertTrue(cExPath.tDeltas.get(vEnd).compareTo(t22) == 0);
        }

    }

    /**
     * Check that APUpperTracingSet returns the correct counter-example path
     * when the time constraint is violated
     */
    @Test
    public void APUpperCounterExamplePathTest() throws Exception {
        cExPathTestCommon(eventsAP, "x AP z upper", TracingSet.APUpper);
    }

    /**
     * Check that AFbyUpperTracingSet returns the correct counter-example path
     * when the time constraint is violated
     */
    @Test
    public void AFbyUpperCounterExamplePathTest() throws Exception {
        cExPathTestCommon(eventsAFby, "x AFby z upper", TracingSet.AFbyUpper);
    }

    /**
     * Check that APLowerTracingSet returns the correct counter-example path
     * when the time constraint is violated
     */
    @Test
    public void APLowerCounterExamplePathTest() throws Exception {
        cExPathTestCommon(eventsAP, "x AP z lower", TracingSet.APLower);
    }

    /**
     * Check that AFbyLowerTracingSet returns the correct counter-example path
     * when the time constraint is violated
     */
    @Test
    public void AFbyLowerCounterExamplePathTest() throws Exception {
        cExPathTestCommon(eventsAFby, "x AFby z lower", TracingSet.AFbyLower);
    }

    /**
     * Check that it can be correctly detected whether or not a
     * ConstraintedTracingSet inhabits a subset of the states of another, which
     * is used for loop-detection and termination
     */
    @Test
    public void stateSubsetTest() throws Exception {
        // Create a legal node to be the "inhabited states"
        ConstrainedHistoryNode<Partition> node = new ConstrainedHistoryNode<Partition>(
                new Partition(new EventNode(new Event(""))), new ITotalTime(0));

        // Create the lists of inhabited states: (0,2,3) and (0,2)
        List<ConstrainedHistoryNode<Partition>> cTSetStates = new ArrayList<ConstrainedHistoryNode<Partition>>();
        cTSetStates.add(node);
        cTSetStates.add(null);
        cTSetStates.add(node);
        cTSetStates.add(node);
        cTSetStates.add(null);
        List<ConstrainedHistoryNode<Partition>> cTSubsetStates = new ArrayList<ConstrainedHistoryNode<Partition>>();
        cTSubsetStates.add(node);
        cTSubsetStates.add(null);
        cTSubsetStates.add(node);
        cTSubsetStates.add(null);
        cTSubsetStates.add(null);

        // Create the tracing sets, and set the created states
        ConstrainedTracingSet<Partition> cTSet = new AFbyLowerTracingSet<Partition>();
        cTSet.setStates(cTSetStates);
        ConstrainedTracingSet<Partition> cTSubset = new AFbyLowerTracingSet<Partition>();
        cTSubset.setStates(cTSubsetStates);

        // cTSubset inhabits a subset of states that cTSet does but not vice
        // versa
        assertTrue(cTSubset.isSubset(cTSet));
        assertFalse(cTSet.isSubset(cTSubset));
    }
}
