// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_trace.proto

package prototrace;

public final class ProtoTrace {
  private ProtoTrace() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class GenericMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use GenericMessage.newBuilder() to construct.
    private GenericMessage() {
      initFields();
    }
    private GenericMessage(boolean noInit) {}
    
    private static final GenericMessage defaultInstance;
    public static GenericMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public GenericMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return prototrace.ProtoTrace.internal_static_prototrace_GenericMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return prototrace.ProtoTrace.internal_static_prototrace_GenericMessage_fieldAccessorTable;
    }
    
    // optional fixed32 src = 1;
    public static final int SRC_FIELD_NUMBER = 1;
    private boolean hasSrc;
    private int src_ = 0;
    public boolean hasSrc() { return hasSrc; }
    public int getSrc() { return src_; }
    
    // optional fixed32 dst = 2;
    public static final int DST_FIELD_NUMBER = 2;
    private boolean hasDst;
    private int dst_ = 0;
    public boolean hasDst() { return hasDst; }
    public int getDst() { return dst_; }
    
    // optional int64 timestamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private boolean hasTimestamp;
    private long timestamp_ = 0L;
    public boolean hasTimestamp() { return hasTimestamp; }
    public long getTimestamp() { return timestamp_; }
    
    // optional bytes payload = 4;
    public static final int PAYLOAD_FIELD_NUMBER = 4;
    private boolean hasPayload;
    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasPayload() { return hasPayload; }
    public com.google.protobuf.ByteString getPayload() { return payload_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasSrc()) {
        output.writeFixed32(1, getSrc());
      }
      if (hasDst()) {
        output.writeFixed32(2, getDst());
      }
      if (hasTimestamp()) {
        output.writeInt64(3, getTimestamp());
      }
      if (hasPayload()) {
        output.writeBytes(4, getPayload());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSrc()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, getSrc());
      }
      if (hasDst()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, getDst());
      }
      if (hasTimestamp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, getTimestamp());
      }
      if (hasPayload()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPayload());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static prototrace.ProtoTrace.GenericMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static prototrace.ProtoTrace.GenericMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static prototrace.ProtoTrace.GenericMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static prototrace.ProtoTrace.GenericMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static prototrace.ProtoTrace.GenericMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static prototrace.ProtoTrace.GenericMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static prototrace.ProtoTrace.GenericMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static prototrace.ProtoTrace.GenericMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static prototrace.ProtoTrace.GenericMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static prototrace.ProtoTrace.GenericMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(prototrace.ProtoTrace.GenericMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private prototrace.ProtoTrace.GenericMessage result;
      
      // Construct using prototrace.ProtoTrace.GenericMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new prototrace.ProtoTrace.GenericMessage();
        return builder;
      }
      
      protected prototrace.ProtoTrace.GenericMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new prototrace.ProtoTrace.GenericMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return prototrace.ProtoTrace.GenericMessage.getDescriptor();
      }
      
      public prototrace.ProtoTrace.GenericMessage getDefaultInstanceForType() {
        return prototrace.ProtoTrace.GenericMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public prototrace.ProtoTrace.GenericMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private prototrace.ProtoTrace.GenericMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public prototrace.ProtoTrace.GenericMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        prototrace.ProtoTrace.GenericMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof prototrace.ProtoTrace.GenericMessage) {
          return mergeFrom((prototrace.ProtoTrace.GenericMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(prototrace.ProtoTrace.GenericMessage other) {
        if (other == prototrace.ProtoTrace.GenericMessage.getDefaultInstance()) return this;
        if (other.hasSrc()) {
          setSrc(other.getSrc());
        }
        if (other.hasDst()) {
          setDst(other.getDst());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 13: {
              setSrc(input.readFixed32());
              break;
            }
            case 21: {
              setDst(input.readFixed32());
              break;
            }
            case 24: {
              setTimestamp(input.readInt64());
              break;
            }
            case 34: {
              setPayload(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // optional fixed32 src = 1;
      public boolean hasSrc() {
        return result.hasSrc();
      }
      public int getSrc() {
        return result.getSrc();
      }
      public Builder setSrc(int value) {
        result.hasSrc = true;
        result.src_ = value;
        return this;
      }
      public Builder clearSrc() {
        result.hasSrc = false;
        result.src_ = 0;
        return this;
      }
      
      // optional fixed32 dst = 2;
      public boolean hasDst() {
        return result.hasDst();
      }
      public int getDst() {
        return result.getDst();
      }
      public Builder setDst(int value) {
        result.hasDst = true;
        result.dst_ = value;
        return this;
      }
      public Builder clearDst() {
        result.hasDst = false;
        result.dst_ = 0;
        return this;
      }
      
      // optional int64 timestamp = 3;
      public boolean hasTimestamp() {
        return result.hasTimestamp();
      }
      public long getTimestamp() {
        return result.getTimestamp();
      }
      public Builder setTimestamp(long value) {
        result.hasTimestamp = true;
        result.timestamp_ = value;
        return this;
      }
      public Builder clearTimestamp() {
        result.hasTimestamp = false;
        result.timestamp_ = 0L;
        return this;
      }
      
      // optional bytes payload = 4;
      public boolean hasPayload() {
        return result.hasPayload();
      }
      public com.google.protobuf.ByteString getPayload() {
        return result.getPayload();
      }
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPayload = true;
        result.payload_ = value;
        return this;
      }
      public Builder clearPayload() {
        result.hasPayload = false;
        result.payload_ = getDefaultInstance().getPayload();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:prototrace.GenericMessage)
    }
    
    static {
      defaultInstance = new GenericMessage(true);
      prototrace.ProtoTrace.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:prototrace.GenericMessage)
  }
  
  public static final class PingPongMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use PingPongMessage.newBuilder() to construct.
    private PingPongMessage() {
      initFields();
    }
    private PingPongMessage(boolean noInit) {}
    
    private static final PingPongMessage defaultInstance;
    public static PingPongMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public PingPongMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return prototrace.ProtoTrace.internal_static_prototrace_PingPongMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return prototrace.ProtoTrace.internal_static_prototrace_PingPongMessage_fieldAccessorTable;
    }
    
    // optional fixed32 src = 1;
    public static final int SRC_FIELD_NUMBER = 1;
    private boolean hasSrc;
    private int src_ = 0;
    public boolean hasSrc() { return hasSrc; }
    public int getSrc() { return src_; }
    
    // optional fixed32 dst = 2;
    public static final int DST_FIELD_NUMBER = 2;
    private boolean hasDst;
    private int dst_ = 0;
    public boolean hasDst() { return hasDst; }
    public int getDst() { return dst_; }
    
    // optional int64 timestamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private boolean hasTimestamp;
    private long timestamp_ = 0L;
    public boolean hasTimestamp() { return hasTimestamp; }
    public long getTimestamp() { return timestamp_; }
    
    // optional string type = 4;
    public static final int TYPE_FIELD_NUMBER = 4;
    private boolean hasType;
    private java.lang.String type_ = "";
    public boolean hasType() { return hasType; }
    public java.lang.String getType() { return type_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasSrc()) {
        output.writeFixed32(1, getSrc());
      }
      if (hasDst()) {
        output.writeFixed32(2, getDst());
      }
      if (hasTimestamp()) {
        output.writeInt64(3, getTimestamp());
      }
      if (hasType()) {
        output.writeString(4, getType());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSrc()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, getSrc());
      }
      if (hasDst()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, getDst());
      }
      if (hasTimestamp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, getTimestamp());
      }
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getType());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static prototrace.ProtoTrace.PingPongMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static prototrace.ProtoTrace.PingPongMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static prototrace.ProtoTrace.PingPongMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static prototrace.ProtoTrace.PingPongMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static prototrace.ProtoTrace.PingPongMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static prototrace.ProtoTrace.PingPongMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static prototrace.ProtoTrace.PingPongMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static prototrace.ProtoTrace.PingPongMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static prototrace.ProtoTrace.PingPongMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static prototrace.ProtoTrace.PingPongMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(prototrace.ProtoTrace.PingPongMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private prototrace.ProtoTrace.PingPongMessage result;
      
      // Construct using prototrace.ProtoTrace.PingPongMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new prototrace.ProtoTrace.PingPongMessage();
        return builder;
      }
      
      protected prototrace.ProtoTrace.PingPongMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new prototrace.ProtoTrace.PingPongMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return prototrace.ProtoTrace.PingPongMessage.getDescriptor();
      }
      
      public prototrace.ProtoTrace.PingPongMessage getDefaultInstanceForType() {
        return prototrace.ProtoTrace.PingPongMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public prototrace.ProtoTrace.PingPongMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private prototrace.ProtoTrace.PingPongMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public prototrace.ProtoTrace.PingPongMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        prototrace.ProtoTrace.PingPongMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof prototrace.ProtoTrace.PingPongMessage) {
          return mergeFrom((prototrace.ProtoTrace.PingPongMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(prototrace.ProtoTrace.PingPongMessage other) {
        if (other == prototrace.ProtoTrace.PingPongMessage.getDefaultInstance()) return this;
        if (other.hasSrc()) {
          setSrc(other.getSrc());
        }
        if (other.hasDst()) {
          setDst(other.getDst());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 13: {
              setSrc(input.readFixed32());
              break;
            }
            case 21: {
              setDst(input.readFixed32());
              break;
            }
            case 24: {
              setTimestamp(input.readInt64());
              break;
            }
            case 34: {
              setType(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional fixed32 src = 1;
      public boolean hasSrc() {
        return result.hasSrc();
      }
      public int getSrc() {
        return result.getSrc();
      }
      public Builder setSrc(int value) {
        result.hasSrc = true;
        result.src_ = value;
        return this;
      }
      public Builder clearSrc() {
        result.hasSrc = false;
        result.src_ = 0;
        return this;
      }
      
      // optional fixed32 dst = 2;
      public boolean hasDst() {
        return result.hasDst();
      }
      public int getDst() {
        return result.getDst();
      }
      public Builder setDst(int value) {
        result.hasDst = true;
        result.dst_ = value;
        return this;
      }
      public Builder clearDst() {
        result.hasDst = false;
        result.dst_ = 0;
        return this;
      }
      
      // optional int64 timestamp = 3;
      public boolean hasTimestamp() {
        return result.hasTimestamp();
      }
      public long getTimestamp() {
        return result.getTimestamp();
      }
      public Builder setTimestamp(long value) {
        result.hasTimestamp = true;
        result.timestamp_ = value;
        return this;
      }
      public Builder clearTimestamp() {
        result.hasTimestamp = false;
        result.timestamp_ = 0L;
        return this;
      }
      
      // optional string type = 4;
      public boolean hasType() {
        return result.hasType();
      }
      public java.lang.String getType() {
        return result.getType();
      }
      public Builder setType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = getDefaultInstance().getType();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:prototrace.PingPongMessage)
    }
    
    static {
      defaultInstance = new PingPongMessage(true);
      prototrace.ProtoTrace.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:prototrace.PingPongMessage)
  }
  
  public static final class Trace extends
      com.google.protobuf.GeneratedMessage {
    // Use Trace.newBuilder() to construct.
    private Trace() {
      initFields();
    }
    private Trace(boolean noInit) {}
    
    private static final Trace defaultInstance;
    public static Trace getDefaultInstance() {
      return defaultInstance;
    }
    
    public Trace getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return prototrace.ProtoTrace.internal_static_prototrace_Trace_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return prototrace.ProtoTrace.internal_static_prototrace_Trace_fieldAccessorTable;
    }
    
    // repeated .prototrace.GenericMessage generic_message = 1;
    public static final int GENERIC_MESSAGE_FIELD_NUMBER = 1;
    private java.util.List<prototrace.ProtoTrace.GenericMessage> genericMessage_ =
      java.util.Collections.emptyList();
    public java.util.List<prototrace.ProtoTrace.GenericMessage> getGenericMessageList() {
      return genericMessage_;
    }
    public int getGenericMessageCount() { return genericMessage_.size(); }
    public prototrace.ProtoTrace.GenericMessage getGenericMessage(int index) {
      return genericMessage_.get(index);
    }
    
    // repeated .prototrace.PingPongMessage ping_pong_message = 2;
    public static final int PING_PONG_MESSAGE_FIELD_NUMBER = 2;
    private java.util.List<prototrace.ProtoTrace.PingPongMessage> pingPongMessage_ =
      java.util.Collections.emptyList();
    public java.util.List<prototrace.ProtoTrace.PingPongMessage> getPingPongMessageList() {
      return pingPongMessage_;
    }
    public int getPingPongMessageCount() { return pingPongMessage_.size(); }
    public prototrace.ProtoTrace.PingPongMessage getPingPongMessage(int index) {
      return pingPongMessage_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (prototrace.ProtoTrace.GenericMessage element : getGenericMessageList()) {
        output.writeMessage(1, element);
      }
      for (prototrace.ProtoTrace.PingPongMessage element : getPingPongMessageList()) {
        output.writeMessage(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (prototrace.ProtoTrace.GenericMessage element : getGenericMessageList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      for (prototrace.ProtoTrace.PingPongMessage element : getPingPongMessageList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static prototrace.ProtoTrace.Trace parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static prototrace.ProtoTrace.Trace parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static prototrace.ProtoTrace.Trace parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static prototrace.ProtoTrace.Trace parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static prototrace.ProtoTrace.Trace parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static prototrace.ProtoTrace.Trace parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static prototrace.ProtoTrace.Trace parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static prototrace.ProtoTrace.Trace parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static prototrace.ProtoTrace.Trace parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static prototrace.ProtoTrace.Trace parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(prototrace.ProtoTrace.Trace prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private prototrace.ProtoTrace.Trace result;
      
      // Construct using prototrace.ProtoTrace.Trace.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new prototrace.ProtoTrace.Trace();
        return builder;
      }
      
      protected prototrace.ProtoTrace.Trace internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new prototrace.ProtoTrace.Trace();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return prototrace.ProtoTrace.Trace.getDescriptor();
      }
      
      public prototrace.ProtoTrace.Trace getDefaultInstanceForType() {
        return prototrace.ProtoTrace.Trace.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public prototrace.ProtoTrace.Trace build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private prototrace.ProtoTrace.Trace buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public prototrace.ProtoTrace.Trace buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.genericMessage_ != java.util.Collections.EMPTY_LIST) {
          result.genericMessage_ =
            java.util.Collections.unmodifiableList(result.genericMessage_);
        }
        if (result.pingPongMessage_ != java.util.Collections.EMPTY_LIST) {
          result.pingPongMessage_ =
            java.util.Collections.unmodifiableList(result.pingPongMessage_);
        }
        prototrace.ProtoTrace.Trace returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof prototrace.ProtoTrace.Trace) {
          return mergeFrom((prototrace.ProtoTrace.Trace)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(prototrace.ProtoTrace.Trace other) {
        if (other == prototrace.ProtoTrace.Trace.getDefaultInstance()) return this;
        if (!other.genericMessage_.isEmpty()) {
          if (result.genericMessage_.isEmpty()) {
            result.genericMessage_ = new java.util.ArrayList<prototrace.ProtoTrace.GenericMessage>();
          }
          result.genericMessage_.addAll(other.genericMessage_);
        }
        if (!other.pingPongMessage_.isEmpty()) {
          if (result.pingPongMessage_.isEmpty()) {
            result.pingPongMessage_ = new java.util.ArrayList<prototrace.ProtoTrace.PingPongMessage>();
          }
          result.pingPongMessage_.addAll(other.pingPongMessage_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              prototrace.ProtoTrace.GenericMessage.Builder subBuilder = prototrace.ProtoTrace.GenericMessage.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addGenericMessage(subBuilder.buildPartial());
              break;
            }
            case 18: {
              prototrace.ProtoTrace.PingPongMessage.Builder subBuilder = prototrace.ProtoTrace.PingPongMessage.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPingPongMessage(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .prototrace.GenericMessage generic_message = 1;
      public java.util.List<prototrace.ProtoTrace.GenericMessage> getGenericMessageList() {
        return java.util.Collections.unmodifiableList(result.genericMessage_);
      }
      public int getGenericMessageCount() {
        return result.getGenericMessageCount();
      }
      public prototrace.ProtoTrace.GenericMessage getGenericMessage(int index) {
        return result.getGenericMessage(index);
      }
      public Builder setGenericMessage(int index, prototrace.ProtoTrace.GenericMessage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.genericMessage_.set(index, value);
        return this;
      }
      public Builder setGenericMessage(int index, prototrace.ProtoTrace.GenericMessage.Builder builderForValue) {
        result.genericMessage_.set(index, builderForValue.build());
        return this;
      }
      public Builder addGenericMessage(prototrace.ProtoTrace.GenericMessage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.genericMessage_.isEmpty()) {
          result.genericMessage_ = new java.util.ArrayList<prototrace.ProtoTrace.GenericMessage>();
        }
        result.genericMessage_.add(value);
        return this;
      }
      public Builder addGenericMessage(prototrace.ProtoTrace.GenericMessage.Builder builderForValue) {
        if (result.genericMessage_.isEmpty()) {
          result.genericMessage_ = new java.util.ArrayList<prototrace.ProtoTrace.GenericMessage>();
        }
        result.genericMessage_.add(builderForValue.build());
        return this;
      }
      public Builder addAllGenericMessage(
          java.lang.Iterable<? extends prototrace.ProtoTrace.GenericMessage> values) {
        if (result.genericMessage_.isEmpty()) {
          result.genericMessage_ = new java.util.ArrayList<prototrace.ProtoTrace.GenericMessage>();
        }
        super.addAll(values, result.genericMessage_);
        return this;
      }
      public Builder clearGenericMessage() {
        result.genericMessage_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .prototrace.PingPongMessage ping_pong_message = 2;
      public java.util.List<prototrace.ProtoTrace.PingPongMessage> getPingPongMessageList() {
        return java.util.Collections.unmodifiableList(result.pingPongMessage_);
      }
      public int getPingPongMessageCount() {
        return result.getPingPongMessageCount();
      }
      public prototrace.ProtoTrace.PingPongMessage getPingPongMessage(int index) {
        return result.getPingPongMessage(index);
      }
      public Builder setPingPongMessage(int index, prototrace.ProtoTrace.PingPongMessage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.pingPongMessage_.set(index, value);
        return this;
      }
      public Builder setPingPongMessage(int index, prototrace.ProtoTrace.PingPongMessage.Builder builderForValue) {
        result.pingPongMessage_.set(index, builderForValue.build());
        return this;
      }
      public Builder addPingPongMessage(prototrace.ProtoTrace.PingPongMessage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.pingPongMessage_.isEmpty()) {
          result.pingPongMessage_ = new java.util.ArrayList<prototrace.ProtoTrace.PingPongMessage>();
        }
        result.pingPongMessage_.add(value);
        return this;
      }
      public Builder addPingPongMessage(prototrace.ProtoTrace.PingPongMessage.Builder builderForValue) {
        if (result.pingPongMessage_.isEmpty()) {
          result.pingPongMessage_ = new java.util.ArrayList<prototrace.ProtoTrace.PingPongMessage>();
        }
        result.pingPongMessage_.add(builderForValue.build());
        return this;
      }
      public Builder addAllPingPongMessage(
          java.lang.Iterable<? extends prototrace.ProtoTrace.PingPongMessage> values) {
        if (result.pingPongMessage_.isEmpty()) {
          result.pingPongMessage_ = new java.util.ArrayList<prototrace.ProtoTrace.PingPongMessage>();
        }
        super.addAll(values, result.pingPongMessage_);
        return this;
      }
      public Builder clearPingPongMessage() {
        result.pingPongMessage_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:prototrace.Trace)
    }
    
    static {
      defaultInstance = new Trace(true);
      prototrace.ProtoTrace.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:prototrace.Trace)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_prototrace_GenericMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_prototrace_GenericMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_prototrace_PingPongMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_prototrace_PingPongMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_prototrace_Trace_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_prototrace_Trace_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto_trace.proto\022\nprototrace\"N\n\016Gener" +
      "icMessage\022\013\n\003src\030\001 \001(\007\022\013\n\003dst\030\002 \001(\007\022\021\n\tt" +
      "imestamp\030\003 \001(\003\022\017\n\007payload\030\004 \001(\014\"L\n\017PingP" +
      "ongMessage\022\013\n\003src\030\001 \001(\007\022\013\n\003dst\030\002 \001(\007\022\021\n\t" +
      "timestamp\030\003 \001(\003\022\014\n\004type\030\004 \001(\t\"t\n\005Trace\0223" +
      "\n\017generic_message\030\001 \003(\0132\032.prototrace.Gen" +
      "ericMessage\0226\n\021ping_pong_message\030\002 \003(\0132\033" +
      ".prototrace.PingPongMessageB\030\n\nprototrac" +
      "eB\nProtoTrace"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_prototrace_GenericMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_prototrace_GenericMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_prototrace_GenericMessage_descriptor,
              new java.lang.String[] { "Src", "Dst", "Timestamp", "Payload", },
              prototrace.ProtoTrace.GenericMessage.class,
              prototrace.ProtoTrace.GenericMessage.Builder.class);
          internal_static_prototrace_PingPongMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_prototrace_PingPongMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_prototrace_PingPongMessage_descriptor,
              new java.lang.String[] { "Src", "Dst", "Timestamp", "Type", },
              prototrace.ProtoTrace.PingPongMessage.class,
              prototrace.ProtoTrace.PingPongMessage.Builder.class);
          internal_static_prototrace_Trace_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_prototrace_Trace_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_prototrace_Trace_descriptor,
              new java.lang.String[] { "GenericMessage", "PingPongMessage", },
              prototrace.ProtoTrace.Trace.class,
              prototrace.ProtoTrace.Trace.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
